export const SEARCH_DATA = [
  {
    id: 'oef0f92oi2e33cs',
    name: 'Home',
    icon: 'document',
    value: '/',
    keywords: 'route/page/home',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, quas.`,
  },
  {
    id: 'jfs92ni4h5lk6nl8',
    name: 'Experience',
    icon: 'document',
    value: '/experience',
    keywords: 'route/page/experience',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, quas.`,
  },
  {
    id: 'po2o43u5ponbh532',
    name: 'Projects',
    icon: 'document',
    value: '/projects',
    keywords: 'route/page/projects',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, quas.`,
  },
  {
    id: 'l3o34oijhbvf823a',
    name: 'Toolbox',
    icon: 'document',
    value: '/toolbox',
    keywords: 'route/page/toolbox',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, quas.`,
  },
  {
    id: 'ji32oi4hb3u50n53',
    name: 'Sandbox',
    icon: 'document',
    value: '/sandbox',
    keywords: 'route/page/sandbox',
    description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, quas.`,
  },
];
